### ISSUE TITLE
서버간 메시징 기능 구축

### ISSUE THREAD

**Issue by mataeLee** [f-lab-edu/matching-taxi#2]
## 개요
Scale-out에 유리하게 설계하여 서버간 메시징 기능을 개발
Redis pub/sub을 이용하여 메시징

## Task
- [x] Redis 연결 설정
- [x] pub/sub 구현
- [x] 통신에 이용되는 Dao, Service layer 구현
- [x] 서버간 통신 메시지 도메인 구현
