### ISSUE TITLE
택시 유저의 지리 데이터 처리

### ISSUE THREAD

**Issue by mataeLee** [f-lab-edu/matching-taxi#6]
## 개요
택시 유저의 지속적인 위치 데이터 업데이트 비즈니스 요구사항 기능 개발
지리 데이터 처리 기능 개발

## Task
- [ ] 택시 유저의 지리 데이터 업데이트 API 호출 처리
- [ ] 지리 데이터 관리 및 CRUD 개발
- [ ] 택시 유저의 매칭 채널과 지리 데이터 논리적 연결
